name: MLOPS practical

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    name: training and evaluation
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up python enviroment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: train the model
        run: python src/train.py
      
      - name: evaluate the model
        run: python src/evaluate.py
      
      - name: checkout code
        uses: actions/checkout@v3
      
      